### ISSUE TITLE
Need to arrange in alphabetical order

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/awesome-twitter-threads#9]

**Comment by dhruvx24** [comment]
Can you please explain more

**Comment by chetanraj** [comment]
The list of the treads are not in alphabetical order, the Javascript Projects to Practice is, at last, it needs to be sorted alphabetically in README.md document

- 2021 Roadmap For Front-End Developers by Trilochan Parida
- Free Web Development Resources by Marko Denic
- Learn CSS Grid by FrontEnd Dude
- Learn CSS Flexbox by FrontEnd Dude
- Optimizing images in your webpage by Santiago
- Optimizing JavaScript code by Santiago
- Resources For Learning React by Pratham
- Javascript Projects to Practice as a Beginner by Trilochan Parida
- Best Web Development Blogs by AnkurGreen heartCode Life Fitness

**Comment by dhruvx24** [comment]
Ok can i take it
